### ISSUE TITLE
予約一覧表示部分をスクロール可能にする

### ISSUE THREAD

**Issue by k-wakatake** [k-wakatake/MTGReserve#3]
## 概要
予約件数が多くなった場合、現在の予約一覧表示では全ての予約が縦に表示され、ページが非常に長くなってしまいます。予約情報の表示部分を固定高さで制限し、内部をスクロール可能にすることで、UIの使い勝手を向上させます。

## 要件
- 予約一覧セクション（#reservation-list）に最大高さを設定する
- 予約件数が多くなった場合は自動的にスクロールバーを表示する
- スクロールバーのデザインはモダンなUIに合わせる
- レスポンシブデザインにも対応する（モバイル表示での適切な高さ設定）

## 変更が必要なファイル
- `styles.css`: スクロール設定のためのCSSを追加
- 必要に応じて `index.html`: 構造の調整が必要な場合

## 提案される変更内容
```css
#reservation-list {
    max-height: 500px; /* 適切な高さに調整 */
    overflow-y: auto; /* 垂直方向のスクロールを許可 */
    padding-right: 5px; /* スクロールバーのためのパディング */
}

/* カスタムスクロールバースタイル */
#reservation-list::-webkit-scrollbar {
    width: 8px;
}

#reservation-list::-webkit-scrollbar-track {
    background: var(--light-bg);
    border-radius: 4px;
}

#reservation-list::-webkit-scrollbar-thumb {
    background-color: var(--primary-light);
    border-radius: 4px;
}
```

## 期待される動作
- 予約件数が少ない場合：通常通り全ての予約が表示され、スクロールバーは表示されない
- 予約件数が多い場合：固定高さを超えた部分はスクロールで表示できる

## タスクの優先度
中：使い勝手を向上させる機能改善
